name: 4diac IDE verification build

on:
  push:
    branches: [ "release", "develop", "freeze", "3.0.x"]
  pull_request:
    branches: [ "release", "develop", "freeze", "3.0.x"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }} 
    name: OS ${{ matrix.os }} Java ${{ matrix.java }} compile
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Set up Java
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.3
    - name: Build with Maven
      uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1.0.1
      with:
       run: >- 
        mvn -V -B -fae -ntp clean verify
    - name: Upload Test Results for Java-${{ matrix.java }}
      if: always()
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/**/target/surefire-reports/*.xml
